name: Example action

on: [push]

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Spectral
      uses: spectralops/spectral-github-action@v1
      with:
        spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
    - name: Spectral Scan
      run: spectral scan